<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.5</version>
		<relativePath/>
	</parent>

	<groupId>com.example.nium</groupId>
	<artifactId>virtual-card</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>

	<name>VirtualCard</name>
	<description>Virtual Card Issuance Platform</description>

	<modules>
		<module>api</module>
		<module>service</module>
	</modules>

	<properties>
		<revision>1.3.0-SNAPSHOT</revision>
		<java.version>17</java.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.example.nium.service</groupId>
				<artifactId>virtual-card-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.example.nium.api</groupId>
				<artifactId>virtual-card-api</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
		</dependency>
	</dependencies>

</project>
